language: python
python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install awscli

jobs:
  include:
    - stage: sync
      if: tag =~ ^v(\d+.?)+.*$
      script:
      #- mkdir ~/.spin && echo $${ENCODED_SPIN_CONFIG} | base64 -d > ~/.spin/config
      - curl -sL https://raw.githubusercontent.com/nagypeterjob-edu/resource-generator/master/get_gen.sh | sh
      - ./gen --destination generated --values resources
      # Upload values to S3
      - aws s3 sync generated/resources s3://$${AWS_S3_BUCKET}/values
      # Deploy spinnaker resources
      #- ls -1 /$(destination)/applications | xargs -I{} spin app save --file /$(destination)/applications/{}
      #- ls -1 /$(destination)/pipelines | xargs -I{} spin pi save --file /$(destination)/pipelines/{}
      